### ISSUE TITLE
Schedule BOF Session at OSSNA

### ISSUE THREAD

**Issue by andyl** [chaoss/wg-value#1]
Open Source Summit North America in San Diego Aug 21-23.

Need someone who connected with the Linux Foundation for intros and/or scheduling.

**Comment by GeorgLink** [comment]
The CFP is open for another week: 
https://events.linuxfoundation.org/events/open-source-summit-north-america-2019/program/cfp/

Depending on the time for this session, I see two options:
* Birds of a Feather (BoF)
* Workshop or Lab

**Comment by andyl** [comment]
Thanks very much for this info @GeorgLink.  I can write up a proposal.  Is there someone out there who can point to example successful proposals?  Is there someone who understands the conference and CFP process who can give guidance and feedback on our proposal?

**Comment by GeorgLink** [comment]
Here are some past submissions
* https://docs.google.com/document/d/1J2cZP4kNpxn4M6r5NGbIV0bqfWbQcdTMlUJIu0is2A4/edit
* https://docs.google.com/document/d/1bdZyAsFmBRq2XvYSvSJfOkRq1gPTAKy9PERlyrItjik/edit
* https://docs.google.com/document/d/16-M2hsv4wwnk5GpDSFLc8EQVNAGkfB7k1GagM4aQ6Kw/edit

Happy review and help revise a draft. Let me know if you have any questions.

**Comment by andyl** [comment]
Here is the draft proposal:

https://docs.google.com/document/d/18VwPz8KP6Q0gFVcE916YhlqGNSBg5LTwmr-7z9eusVA/edit?usp=sharing

@GeorgLink and @germonprez please have a look and I'll submit after you approve.

**Comment by germonprez** [comment]
Thanks @andyl . I've taken a pass at it.

**Comment by GeorgLink** [comment]
Looks good, I made minor edits.

We can chat about this on the first call on Friday.

**Comment by andyl** [comment]
@GeorgLink and @germonprez - thanks for your edits - I will submit after our Friday call.

**Comment by andyl** [comment]
Done.  https://linuxfoundation.smapply.io/tsk/9159844/frm/15583747/
