### ISSUE TITLE
Release Notes - 2021-02

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-value#113]
This issue was created to capture the continuous contribution notes. Insight from comments will be used to create the regular release notes.

Example comments could be:

name of new metric and date of release
descriptions of changes to existing metric
Changes to focus areas or restructuring of WG

**Comment by GeorgLink** [comment]
#120 - Rename `Social Currency Metric System` to `Social Listening`

**Comment by klumb** [comment]
social listening and project popularity

**Comment by klumb** [comment]
Closing for release 2021-03
