### ISSUE TITLE
Change "pull request" language to "change requests"

### ISSUE THREAD

**Issue by mbbroberg** [chaoss/wg-value#119]
To align to Evolution terminology. To link to the page on chaoss.community.

**Comment by Kartik-Khandelwal** [comment]
want to work on this issue.
show me stating path.

**Comment by GeorgLink** [comment]
Hi @Kartik-Khandelwal, 

The Evolution Working Group changed their metric names from `reviews` to `change requests` -- which are `pull requests` in GitHub and `Merge Requests` in GitLab. 

To complete this issue, you would go through files in this repository, looking for mentions of metrics around reviews, pull requests, and merge requests to replace all of them with the new metric name `change requests`.

Please let us know if you have any questions.

**Comment by Kartik-Khandelwal** [comment]
[number of reviews](https://github.com/chaoss/wg-evolution/blob/master/metrics/Reviews.md)
Do I need to change this **review** also to **change requests**.

it will become -> [number of change requests](https://github.com/chaoss/wg-evolution/blob/master/metrics/Reviews.md)

**Comment by Kartik-Khandelwal** [comment]
### CLARIFICATION
#### I had to change : 
All the **'metrices'** to **'change requests'** which are around reviews, pull requests, and merge requests ?
