### ISSUE TITLE
Social Listening - Continuous Metric Release Candidate

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-value#121]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Social Listening

GitHub location: https://github.com/chaoss/wg-value/blob/master/focus-areas/communal-value/social-listening.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by klumb** [comment]
This metric is a revised version of the SCMS metric 
See #75

**Comment by rpaik** [comment]
I think the term `codex` needs to be defined somewhere. I see the term throughout the page, but not 100% what it means. 

Also, the font inside two tables look different from what we use elsewhere in CHAOSS pages. Should we try to be consistent with fonts?

**Comment by germonprez** [comment]
Regarding Codex, I always think of it like a codebook. However, a quick scan of the Internet and I don't think I'm right. I honestly think it is just a book to track thinks. Maybe we just call it 'book'

**Comment by germonprez** [comment]
Looking at the markdown, I don't think the font is different.

**Comment by klumb** [comment]
Closing for release
