### ISSUE TITLE
Adding Academic Value Focus Area

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-value#123]
This issue was created to capture discussion around the creation of an academic value focus area.

**Comment by klumb** [comment]
Scope will likely need to include researchers who create software, use software, and institutional value.

 A key issue here is that researchers who create software need credit toward tenure.

**Comment by klumb** [comment]
**Goal: Identify the degree to which a project is valuable to researchers and academic institutions**

**Comment by GeorgLink** [comment]
Do we have any metrics in here that would be included in the release? We publish a focus area only if we have metrics

**Comment by klumb** [comment]
I think we are still in the early stages here. I would say no to release. Removing the label.

**Comment by klumb** [comment]
Proposed metric:
1. Software Citations
2. Funding

**Comment by vinodkahuja** [comment]
@GeorgLink @klumb Since we have metric (i.e. Academic Open Source Project Impact) ready for release under this focus area. I propose changing the label from discussion to Metrics Candidate release for the upcoming release.

**Comment by GeorgLink** [comment]
Done

**Comment by klumb** [comment]
Closing for Release
