### ISSUE TITLE
Value Report

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-value#125]
Previously I have suggested building a Value Prospectus Dashboard that funders could use to determine the value of project when making decisions about investment.

Now that we have the community report initiative in place. I think it is worth revisiting this idea.

What would a value community report look like?

I propose starting with the organization focus area but I am also very interested in what this would look like for the proposed academic focus area.

**Comment by vinodkahuja** [comment]
Discussed in today's value meeting we will leave it open here until we have a clear process for the metric model.

**Comment by vinodkahuja** [comment]
can re-emerge as different models around funding in future.
