### ISSUE TITLE
Project Popularity - Metric Release Candidate

### ISSUE THREAD

**Issue by vinodkahuja** [chaoss/wg-value#127]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Project Popularity

GitHub location: https://github.com/chaoss/wg-value/blob/master/focus-areas/communal-value/project-popularity.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by klumb** [comment]
@vinodkahuja That last link is bad

See all release candidates of metrics are at:
https://chaoss.community/metrics/

**Comment by vinodkahuja** [comment]
@klumb Thanks for the update

**Comment by rpaik** [comment]
How do you define "popular contributors" to a project? Isn't this subjective and also difficult to measure?

**Comment by germonprez** [comment]
Good point @rpaik I think this list point could just be removed. If this were defined in a different metric, it may be a different story but it isn't :)

**Comment by germonprez** [comment]
Issued a PR in #136

**Comment by rpaik** [comment]
Thanks @germonprez 😄

**Comment by GeorgLink** [comment]
Closing issue. It was included in release 2021-03
