### ISSUE TITLE
Feedback on Focus Area: Innovation Value

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-value#13]
This issue is for developing Value WG focus area: **Innovation Value**

Goal of this focus area: Evaluating open source project development for comparing with in-house and outsourcing options

Please suggest changes, add questions, and provide feedback inside the google doc:
https://docs.google.com/document/d/1q40ljJZ93AYbaxH1jewLWzHRKe892uavD2bgSA3ybp0/edit#

**Comment by mpgjon** [comment]
Moving comments out of Google doc to here:) 

Questions for companies who wish to measure "innovoation" value

If we didn’t use “this piece” of open source technology, we’d have to build it, or buy it. How much would it cost us to do so?  Calculation framework to include: 

- Estimated cost to build from scratch (offer a low, medium, high estimate framework and average them  Do this for BOTH dollar cost and labor time cost).

- Estimated cost of licensing (offer a low, medium and high licensing price input, and average them).

- Estimated Opportunity Cost calculation

Work with product owners to estimate the real dollar value of a feature being delivered (eg, how much additional revenue or savings are estimated to be delivered by a feature in a given year?)

Take time cost from A  (how many dev hours it would take to build), subtract those hours from how many dev hours your current team can provide in a given time period (for example, 160 hours = 1 dev/month).

An example: 
If a given feature is going to save $120,000/year, then the opportunity cost of each month it's **not** implemented is $10k per month.

If that feature was going to require 160 dev hours to complete; but instead that dev has to write something else that could have been done in open source instead, then the opportunity cost to the business of NOT using an Open Source solution is $10k/month.

BTW, the opportunity cost ties directly to a companies capacity for teams to have TIME to innovate:) So we could say "innovation opportunity cost" - might be more contextual.

**Comment by germonprez** [comment]
Thanks @mpgjon. I think a lot of these values are going to have to be local parameters used by individual companies. I know that right now, there is similar discussion on a release candidate metric around labor investment.

**Comment by mpgjon** [comment]
Thanks @germonprez  - 100% agree.  Is there some sort of web-based value calculator on the roadmap?  We could help individual companies understand what parameters might be most helpful with a guided calc of some sort (we could also use a set of web-based calcs to anonymously gather inputs as research data points - as long as we disclose the anonymous collection)

**Comment by germonprez** [comment]
I don't think I'd call it a roadmap but here is a link to the candidate metric for Investment by Organization: 
https://chaoss.community/metric-labor-investment-by-organization/

You'll see that this starts with Issues but PRs will play a role in future versions. Along with other things, I suspect. 

This is a start in this area. In short, the idea is that people could download raw data (CSV) and then manipulate it locally. I think a next step would be to start building this type of manipulation into a UI so that you don't have download the data.

**Comment by mpgjon** [comment]
Thanks for the link - is that page in the chaoss/website repo?  Two of the three literature links at the bottom don't seem to resolve:) (Creating an OSPO, and OS in the Enterprise).

**Comment by andyl** [comment]
@mpgjon - thanks for these notes.  I expect value will be expressed in different forms depending on business context.  One context is economic cost to get the work done (like a buy vs build or inhouse/outsource evaluation).  Another context is economic value and competitive advantage of achieving a dominant market position.  For example - https://www.forbes.com/sites/jeanbaptiste/2019/07/01/bill-gates-admits-that-his-biggest-mistake-was-letting-android-win-costing-microsoft-400-billion/#17d9a9205689

**Comment by andyl** [comment]
Closing now that our first metrics are published.
