### ISSUE TITLE
Feedback on Focus Area: Labor Investment

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-value#14]
This issue is for developing Value WG focus area: **Labor Investment**

Goal of this focus area: Estimating the labor investment in open source projects.

Please suggest changes, add questions, and provide feedback inside the google doc:
https://docs.google.com/document/d/1AJ-CA1gwXRuAeZYe6sKjBM9eaCPME1dGqWT5kRvroG0/edit#

**Comment by vchrombie** [comment]
I would like to help with the reference implementations of the value metrics. :slightly_smiling_face:

**Comment by andyl** [comment]
@vchrombie let's use #21 to discuss reference implementation

**Comment by andyl** [comment]
This is now posted in our repo.

**Comment by klumb** [comment]
This is probably superseded by #29

Close?

**Comment by andyl** [comment]
Closed.
