### ISSUE TITLE
Standard Structure for README.md in each WG repo

### ISSUE THREAD

**Issue by yash2002109** [chaoss/wg-value#143]
Hi everyone,

While standardizing the repositories, I noticed that the [README](https://github.com/chaoss/wg-value/blob/master/README.md) file of each working group has a different structure. After discussing with @GeorgLink, I have drafted a proposal for a common structure that can be implemented across these README files. I have also replicated the same as a [template](https://github.com/yash2002109/chaoss-workspace/blob/main/WG-README-template.md).

Link: https://docs.google.com/document/d/1pfipIiaemdtdiDQpvY7jOKhKzsv_3lXLLsbJiByl5GU/edit?usp=sharing

Please provide your thoughts and suggestions regarding the proposal.

**Comment by GeorgLink** [comment]
@yash2002109 , can you please take a look at the repo and let us know here if there is anything still missing before we can close this issue?

**Comment by yash2002109** [comment]
Thanks @GeorgLink, 

The README was updated by #153 and now follows the template.

**Comment by GeorgLink** [comment]
Thank you!
