### ISSUE TITLE
Value for a project to be part of a larger ecosystem

### ISSUE THREAD

**Issue by nicorikken** [chaoss/wg-value#154]
There was an earlier issue #15 but I think that had a different scope, so I'll create a new one.

In my work within the LFEnergy I can see a deliberate effort for projects to build towards an ecosystem in which solutions complement each other. **The reasoning being that projects will increase their value by teaming up, with the whole being greater than the sum of their parts.** Just look at the CNCF projects, their are a real ecosystem, just look at the [CNCF Landscape page](https://landscape.cncf.io/) In the current metrics I only see dependencies within the evolution group, but nothing that highlights the value of being part of an ecosystem.

Or rather than speaking of an ecosystem, perhaps consider if there are other projects it is know to work well with.

In terms of how to measure, one could multiply some existing values to a certain degree. Then again one might also reason that if an ecosystem adds to the popularity of a project, its effect should already be represented in the measurable popularity.

**Comment by germonprez** [comment]
@nicorikken this is brilliant! Thanks for sharing this. Yes, I think that this would be an excellent candidate for a metric and even though I've seen the landscape maps that you mention, I had never considered what you are talking about. Thanks.

**Comment by vinodkahuja** [comment]
@nicorikken thank you for sharing this great idea. Looking forward to meeting you in our upcoming value meeting to discuss this in more detail.

**Comment by vinodkahuja** [comment]
As per today's value working group discussion, @nicorikken will draft a metric on how projects drive value from the ecosystem.
