### ISSUE TITLE
Project Recommendability (previously Contributor Recommendability) 

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-value#161]
This issue is created to collect comments about the rolling release of "______"

This metric can be found here: https://docs.google.com/document/d/1P-Xf2tdXEwg9FH6hANet68paUzadvahI3dW4IGuxk0g/edit#heading=h.wmfp9nxbbdwc 

Once pull request #176 is merged this link will not work
https://github.com/chaoss/wg-value/blob/main/focus-areas/communal-value/contributor-recommendability.md
instead the following link will work 
https://github.com/chaoss/wg-value/blob/main/focus-areas/communal-value/project-recommendability.md

**Note**: This metric is being developed using a Google Doc, and the "Convert to Markdown" add on.

See all release candidates: https://chaoss.community/metrics/

## CHAOSS Metric Quality Checklist
This checklist is used for new and updated metrics to ensure we follow CHAOSS quality standards and processes. Below checklist items don’t have to be completed all at once: create the metric release candidate issue first and then start working on the checklist.

### Process

- [x] Create the “review issue” in the authoring WG’s repo for comments during review period and paste this template in
- [x] Create pull request to edit or add metric to WG’s repo (after checking Content Quality and Technical Requirements below)
- [x] Add the new metric or metric edit to release notes issue in working group repo
- [x] Update the [Metrics Spreadsheet](https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit)
- [x] Create issue in [CHAOSS/Translations repository](https://github.com/chaoss/translations) to kick-off translation to other languages (please use the the translation issue template)
- [x] "Metric Candidate Release" label added to the metric release candidate issue.
- [ ] Metric was added to website

**When above steps are completed:**

- [ ] Announce new/updated metric on mailing list, newsletter, community Zoom call, and Twitter. This can be coordinated with the community manager.

### Content Quality

- [x] Required headings are filled in, including Questions.
- [x] Description provides context to metric
- [x] Objectives list sample uses for the metric and desired outcomes
- [x] If any, DEI uses of the metric are included Objectives
- [x] Optional headings that have no content were removed
- [x] Contributors section lists those contributors that want to be named
- [x] The name of the metric is the same in (1) metric heading, (2) metric file name, (3) focus area, (4) metrics spreadsheet, (5) “review issue”, (6) translation issue, and (7) website

### Technical Requirements

- [x] Message in the metric markdown file that the metric will be part of the next regular release is at top of page and the links are correct (this is in the [metric template](https://github.com/chaoss/metrics/blob/master/resources/metrics-template.md))
- [x] Metric file name is the full metric name and only contains lower case letters and hyphens (“-”) for spaces
- [x] Images are included using markdown and relative links (as described in the metrics template)
- [x] Images have at least one empty line above and below them
- [x] Ensure images are placed in image folder and followed [naming convention](https://github.com/chaoss/metrics/blob/master/resources/metrics-template.md)
- [x] If new focus area is created, ensure focus area is added to wg repo readme and focus area folder readme
- [x] Within the focus area, add the metric in the table and provide the link to the metric and metric question
- [x] Ensure tables within metric are converted as image and placed in the image folder (both original MD and screenshotted PNG format) and follow the naming convention
- [x] No HTML code in the metrics markdown file

**Comment by vinodkahuja** [comment]
@sgoggins Is this part of the current release or next release.

**Comment by GeorgLink** [comment]
> @sgoggins Is this part of the current release or next release.

This metric was submitted after the metric freeze and should be considered for the next release: 2022-03.

**Comment by klumb** [comment]
The name of this metric is inaccurate. It should be Project Recommendability. 
Although, recommendability, in general, is a difficult word for a metric title so I would re think it.

**Comment by vinodkahuja** [comment]
@klumb name is correct. here is the correct link to the document finalized in last value working group meeting.

https://docs.google.com/document/d/1NIUIBGHJDwhht9lXt66uoSP4CfKvD4AHwEsVa4bDKZE/edit

**Comment by vinodkahuja** [comment]
@klumb I thought you are saying the name is incorrect in the document. After rereading your comment, I assume you are proposing the new name i.e. Project Recommendability. We can consider that and discuss it in our upcoming value meeting.

**Comment by klumb** [comment]
> @klumb I thought you are saying the name is incorrect in the document. After rereading your comment, I assume you are proposing the new name i.e. Project Recommendability. We can consider that and discuss it in our upcoming value meeting.

Yes, I think this metric really needs a new name.

**Comment by klumb** [comment]
Please create an issue for this metric in the translations repo

**Comment by germonprez** [comment]
@vinodkahuja could you do this?

**Comment by vinodkahuja** [comment]
Translation request done

**Comment by rpaik** [comment]
The name of the metrics is a bit misleading to me. When I first read it, I thought it was to rate the contributor (or a community member). But it sounds like to to rate a project or community?

**Comment by eyehwan** [comment]
I have updated translation.

**Comment by germonprez** [comment]
This metric is ready for release.
