### ISSUE TITLE
Change default git branch to 'main'

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-value#162]

**Comment by GeorgLink** [comment]
Done

![Screen Shot 2021-10-05 at 11 51 36 AM](https://user-images.githubusercontent.com/8862021/136067575-9986bf6d-842f-40d7-a435-832844357a37.png)

**Comment by GeorgLink** [comment]
This broke the website:
chaoss/website#669

Waiting for website to update.

**Comment by GeorgLink** [comment]
This issue can be closed when the WG discussed the change during a meeting.

**Comment by vinodkahuja** [comment]
Done
