### ISSUE TITLE
Create Grant Funding Table

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-value#19]
This issue is to track development of the grant funding table.
The goal is to move this into the repository as a markdown file.

https://docs.google.com/spreadsheets/d/1Bjxrv3OIosyiBgzfaSLdAeLqBVpZZZ0TFpHCCDu7QS8/edit#gid=0

**Comment by vchrombie** [comment]
Moving the sheet details into the repository is a good idea so that we can have everything in one place. I would like to add this now if you feel the sheet is in good shape or I can do it once everything needed is added. :slightly_smiling_face:

**Comment by GeorgLink** [comment]
During the call yesterday, we decided to keep the data in the google sheet. What you can do is add the sheet as a link to the README.

**Comment by vchrombie** [comment]
> During the call yesterday, we decided to keep the data in the google sheet. What you can do is add the sheet as a link to the README.

Ok. I will do it. :slightly_smiling_face:

**Comment by andyl** [comment]
I added the link to the README.
