### ISSUE TITLE
Live site for Labor-Investment Metric

### ISSUE THREAD

**Issue by andyl** [chaoss/wg-value#21]
At this point we have agreed:
- to get started we will focus on the labor-investment metric
- we would like our work to be informed by live code
- we will use parametrized metrics - PRs, issues, etc, combined with private parameters (labor rates etc)
- getting started by exporting common metrics via JSON/CSV is OK (private parameters can be plugged into the spreadsheet...)

I propose the following approach...

Phase 1) Minimal Live Site
- live instance of augur - no customizations
- data ingestion using off-the-shelf tools (perceval etc.)
- able to display common metrics for a handful of projects
- able to export metrics to JSON or CSV

Phase 2) On-Page Parameterized Metrics
- customization of augur pages to allow parameterization
- able to plug in private parameters w/o needing to use spreadsheets

Phase 3) Private Metrics Survey
- ability to capture and anonymize private metrics
- ability to summarize and display learnings re: private metrics

@sgoggins @GeorgLink WDYT?

@all - I have a bare-metal server that we can use to host the VM instance if that would be helpful...

@vchrombie - let's see what sean and georg have to say here, then lay out a plan of action so that you can get hands-on with the code.  does that sound ok?

**Comment by andyl** [comment]
Note: there is a live site "value.augurlabs.io".  The site exists on the old augur implementation (AFAIK), and has not yet been exercised.

**Comment by mbbroberg** [comment]
Since we're working on a new direction for the Value WG, I'll archive this issue. 

For others following along, please see the [problem statement](https://github.com/chaoss/wg-value#problem-statement) and let me know if you'd like to participate.
