### ISSUE TITLE
VMG OSPO Interview Plan

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-value#23]
We are working in this google doc: 

https://docs.google.com/document/d/19Ye6V3N8eH59ekI81-2RTzn-TD21ctLr3DFprYGymac/edit#heading=h.w5n40b52ft70

**Comment by mbbroberg** [comment]
Since we're working on a new direction for the Value WG, I'll archive this issue. 

For others following along, please see the [problem statement](https://github.com/chaoss/wg-value#problem-statement) and let me know if you'd like to participate.
