### ISSUE TITLE
Mozilla Proposal - Value Metrics

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-value#24]
Mozilla Research Grants 2019H1:
https://mozilla-research.forms.fm/mozilla-research-grants-2019h1/forms/6510

We are working in this document:
https://docs.google.com/document/d/1I1ztF0TCSUGtTj_hnhBfsG3TYNymug4fWIGh1531xlE/edit#

**Comment by andyl** [comment]
Going to pass on this one.
