### ISSUE TITLE
Candidate Release Comments (Project Popularity)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-value#26]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Popularity

GitHub location: https://github.com/chaoss/wg-value/blob/master/focus-areas/living-wage/project_popularity.md

Release candidate: https://chaoss.community/metric-project-popularity

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

Important Dates

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by Nebrethar** [comment]
This was noted in the community meeting on July 9th, 2019.

Requesting more information on sections 3 to 6.

**Comment by foundjem** [comment]
Programming language[1][2] can also influence the popularity of a project. 

1. Popularity, Interoperability, and Impact of Programming Languages in 100,000 Open Source Projects
2. What Attract Newcomers to Onboard on OSS Projects? TL;DR: Popularity

**Comment by vinodahujauno** [comment]
Following are other proxy measures used to measure project popularity.
1. Number of source code download
2. Number of subscriber
3. Number of stars
4. Number of watchers
5. Number of followers
6. User ratings
7. Appearance on the top list of google search or other blogs

**Comment by germonprez** [comment]
@andyl, I suggest that this metric is also table this composite metric until a later Metrics version release.

**Comment by GeorgLink** [comment]
At the CHAOSS level, we have not fully worked out how composite metrics will be expressed. This metric is a trailblazer in that regard. I also suggest postponing it until the next release to make sure we have the source metrics in place and can think about how to represent composite metrics.

**Comment by germonprez** [comment]
Perhaps the v-index is another potential measure: https://opensource.com/article/18/5/metrics-project-success

**Comment by germonprez** [comment]
@klumb @andyl @GeorgLink Please remove this as a candidate metric for Version 1 as discussed in the Value call on Friday, July 19. This metric will be readdressed in a future metrics release.

**Comment by klumb** [comment]
#197 removes this from release

**Comment by GeorgLink** [comment]
Thanks @klumb

**Comment by GeorgLink** [comment]
closing issue, because Project Popularity is no longer a release candidate
