### ISSUE TITLE
Candidate Release Comments (Organizational Project Skill Demand)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-value#27]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Organizational Impact

GitHub location: https://github.com/chaoss/wg-value/blob/master/focus-areas/living-wage/organizational-project-skill-demand.md 

Release candidate: https://chaoss.community/metric-organizational-project-skill-demand

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

Important Dates

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by Nebrethar** [comment]
This was noted in the community meeting on July 9th, 2019.

Requesting more information of sample and known implementations (5 and 6)

**Comment by germonprez** [comment]
@andyl I suggest that this metric either needs to be developed in much more detail or I think it should be removed for Metrics Version 1 release. Ultimately, I suggest this metric is tabled until the next metrics release version.

**Comment by mpgjon** [comment]
+1 on more development here.

**Comment by sgoggins** [comment]
I think what this metric is getting at is both contribution diversity of organizations, as well as consumption diversity and volume of consumption by downstream projects. We might consider incorporating the V-Index. https://opensource.com/article/18/5/metrics-project-success

**Comment by klumb** [comment]
These links are all dead and the website is pointing to a 404 now.

**Comment by germonprez** [comment]
Was there a name change somewhere along the line?

**Comment by klumb** [comment]
Renamed organizational impact - looking at it now - will update all relevant information.

**Comment by klumb** [comment]
404s are fixed and relevant information on the website was edited to reflect the change.

**Comment by klumb** [comment]
The header for this metric is long. Suggest just calling it "Organizational Impact"  rather than "Downstream Organizational Impact of a Project Software"

Also, the question no longer reflects the objective of the metric.

**Comment by andyl** [comment]
OK to release.
