### ISSUE TITLE
Candidate Release Comments (Project Velocity)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-value#28]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Project Velocity

GitHub location: https://github.com/chaoss/wg-value/blob/master/focus-areas/labor-investment/project_velocity.md

Release candidate: https://chaoss.community/metric-project-velocity

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

Important Dates

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by germonprez** [comment]
@andyl the cncf link (to the sample visual) is returning a 404

**Comment by andyl** [comment]
Ready for release.

**Comment by GeorgLink** [comment]
metric ready for release
