### ISSUE TITLE
Candidate Release Comments (Labor Investment)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-value#29]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Labor Investment

GitHub location: https://github.com/chaoss/wg-value/blob/master/focus-areas/labor-investment/labor_investment.md

Release candidate: https://chaoss.community/metric-labor-investment

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

Important Dates

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by germonprez** [comment]
@andyl the CSV link is leading to a 404

**Comment by andyl** [comment]
OK to release.
