### ISSUE TITLE
Metrics Candidate Release Label

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-value#30]
@andyl 

Please create a "Metrics Candidate Release" tag that matches the wording and color from the other work groups.

Here is an example:
chaoss/wg-evolution#189

**Comment by GeorgLink** [comment]
Done. Label created: https://github.com/chaoss/wg-value/labels/Metrics%20Candidate%20Release

**Comment by klumb** [comment]
Thanks!

Cheers, 


Kevin Lumbard, M.S. PMP (he/him/his)
University of Nebraska at Omaha
College of Information Science and Technology
PKI 367

“Design is all about problem solving. So when I see a project without a problem, I create one” - Anonymous Problem Solver
