### ISSUE TITLE
Validation for approach to manual data collection

### ISSUE THREAD

**Issue by mpgjon** [chaoss/wg-value#33]
As talked about on this morning's Value working group call, I kinda threw out there that maybe we could create a survey front-end pattern for data collection.  @GeorgLink reminded me about LimeSurvey, and I did a quick install and mocked up a sample HR survey with some wild guesses about impact of FOSS on talent acquisition and retention for testing here: 

https://the3laws.net/CHAOSS/index.php/551267?lang=en 

I'm not a real developer (I only play one in the movies...), but I have enabled the JSON API backend service in the LimeSurvey config, and it appears you can get an export of survey results: https://api.limesurvey.org/namespaces/default.html (either via export, or a full db dump... it would be nicer if we could just regularly GET results... but I don't see that option).

Anyway, if someone wants to try making some experimental calls against the API on the above install and assess output suitability for ingestion into GrimoireLab or Augur, let me know and I can get you some credentials for making the calls if it's worth pursuing further.

**Comment by GeorgLink** [comment]
This looks great. Thank you!

**Comment by mbbroberg** [comment]
Since we're working on a new direction for the Value WG, I'll archive this issue. 

For others following along, please see the [problem statement](https://github.com/chaoss/wg-value#problem-statement) and let me know (or join our next meeting) if you'd like to participate.
