### ISSUE TITLE
Where does funding justification fit into VMG?

### ISSUE THREAD

**Issue by mbbroberg** [chaoss/wg-value#57]
Hi all, I'm very happy to see this group together. I'm circling back in to the CHAOSS space now that I have some time to potentially contribute. My question: is there a part of this effort that collects successful evaluations and justification of continued community investment? 

The context: I'm thinking from a corporate technology company perspective, where community groups are well funded for a short period of time, then ultimately shift into looking for ROI where they aren't the strongest. In the past that's looked like getting shoved into digital demand generation or social media marketing or bug fixes or even sales conversions. 

I'm interested in aggregating successful data-driven explanations for community programs, whether its in the shape of an OSPO, DevRel, or influencer program (think Microsoft MVP). Is that aligned with the objectives of any of [the focus groups](https://github.com/chaoss/wg-value/tree/master/focus-areas)? 

For additional context, I wrote about some of this here: 

- https://medium.com/@mbbroberg/the-value-of-community-metrics-4945dc752d42
- https://medium.com/@mbbroberg/community-metrics-whats-the-roi-of-stickers-640d93b73cd3
- https://medium.com/@mbbroberg/community-metrics-share-of-voice-b51d15f38366

And I've started to collect other people's success stories from recent conferences and plan to present the aggregate as part of the next CHAOSScon. Last but not least, I'm planning to be on the next working group meeting, so let's chat 😄

**Comment by germonprez** [comment]
Hi @mbbroberg. Thanks for the links. Nice reads over some coffee this morning. I think that the work you are doing is a great fit with the Value WG. Let's certainly chat more on how your insights can be captured. Do you think that you can capture some of your thoughts based on the metrics templates that we have at: 

https://github.com/chaoss/metrics/blob/master/activity-metrics/metric-template.md

**Comment by GeorgLink** [comment]
Hi @mbbroberg. Indeed, great thoughts on community value and a definite fit for the Value WG. 

The next Value WG meeting is next year -- we are taking a break over the holidays. I do look forward to discussing this more. In the meantime, if you want to explore how to express your thoughts through the template that @germonprez shared, I'd be happy to work with you on that.

**Comment by mbbroberg** [comment]
Fixed in #70 🎉
