### ISSUE TITLE
Activate DCO bot

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-value#6]
@vchrombie reminded me about this issue with his pull request #5

This issue is to activate [protobot/dco](https://github.com/apps/dco) (or similar bot) to check that all commits have a sign-off. The CHAOSS Project Charter requires that all contributions are signed-off. 

For users of the git command line interface, a sign-off is accomplished with the `-s` as part of the commit command: `git commit -s -m 'This is a commit message'`

For users of the GitHub interface, a sign-off is accomplished by writing `Signed-off-by: Your Name <YourName@example.org>` into the commit comment field. This can be automated by using a browser plugin like [scottrigby/dco-gh-ui](https://github.com/)

**Comment by vchrombie** [comment]
The organization members can add this.

**Comment by GeorgLink** [comment]
I can activate the DCO bot.

@andyl are you okay with this?

**Comment by andyl** [comment]
What is the DCO bot?

**Comment by GeorgLink** [comment]
> Is there a less intrusive way to do this? Make it part of the code of conduct or some such?

We extensively discussed this over the last months and the same concerns were raised.  Unfortunately, we do not have an easier way. 

Since we are going to activate the DCO bot on all repositories, the question is whether the VMG is ready.

**Comment by andyl** [comment]
@GeorgLink - In that case please proceed.  I'll do a test of a signed commit now.  

Also: can you point me docco that describes how to activate a DCO bot??

**Comment by andyl** [comment]
OK I pushed a signed commit - piece of cake.  Does it need to be verified by GitHub?  Is there a CHAOSS guide for DCO, signing & verification?

**Comment by GeorgLink** [comment]
DCO bot is active.

> OK I pushed a signed commit - piece of cake.

Awesome!

> can you point me docco that describes how to activate a DCO bot??

https://github.com/apps/dco

> Does it need to be verified by GitHub?

No, it does not need to be verified by GitHub. Although, it would be a good idea.

> Is there a CHAOSS guide for DCO, signing & verification?

Only what is in the CONTRIBUTING.md files.
