### ISSUE TITLE
Release Candidate Comments (Job Opportunities)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-value#63]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Job Opportunities**

GitHub location: https://github.com/chaoss/wg-value/blob/master/focus-areas/living-wage/job-opportunities.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
Looks Good

**Comment by klumb** [comment]
I am marking this metric as ready for release and closing. Please reopen if that is not the case.
