### ISSUE TITLE
Reframe existing metrics into the new mission

### ISSUE THREAD

**Issue by mbbroberg** [chaoss/wg-value#73]
There are existing valuable metrics, currently under the [/archived](https://github.com/chaoss/wg-value/tree/master/metrics/archived) folder, that we would like to have in the next release of CHAOSS to provide continuity of metrics. 

:: updated April 10th :: 

The last meeting of the Value WG determined there are plenty of paths forward for the metrics currently under 'archive,' and we intend to bring them into the fold. This issue will close once that's done. 

:: update May 7th :: 

We may be closer to finding homes and reframing of these metrics. Please volunteer to shepherd them back into the project!

**Comment by germonprez** [comment]
I'm generally of the mind that we should not remove or archive the prior approved metrics. We should work towards a way to incorporate them ... perhaps if we need to reframe the Focus Group headings, that might be a way to go.

**Comment by samanthavenialogan** [comment]
I don't think I have the context or background necessary to really weigh in
but as someone whose metric is in that spot.... I agree.  I don't think
that defaulting all of the metrics to not applicable moving forward with
the new mission is a good idea. There are hidden allowances there that
people may be using and our understanding of whether they provide use in
accordance with the mission may not line up with how people use them on
their end.


Samantha Venia Logan
Co-Founder of SociallyConstructed.Online
307-274-5516  | samantha@SociallyConstructed.Online
6715 Autumn Ridge Dr. Unit 2, Fort Collins CO., 80525

Call me for a free marketing consultation! 307-274-5516

**Comment by GeorgLink** [comment]
I believe we have established during the calls that we want to preserve the metrics and the conversation is ongoing across issues and our bi-weekly meetings.

**Comment by mbbroberg** [comment]
> I'm [Matt G] generally of the mind that we should not remove or archive the prior approved metrics. We should work towards a way to incorporate them.

100% agreed. I had a rough first draft of how to move forward, and as I continue to learn from the history of the group I see lots of opportunity to clarify the usage of previous metrics so industry has a path toward usage in the context of this working group. 

To that point, I opened #46 after learning more from @samanthavenialogan and team. 

> I believe we have established during the calls that we want to preserve the metrics and the conversation is ongoing across issues and our bi-weekly meetings.

Yes, exactly. 

--

This issue will be resolved by PRs for each of the existing metrics being resubmit.

**Comment by mbbroberg** [comment]
This can close due to reframing completed in #93
