### ISSUE TITLE
Reframing job opportunity under the new scope

### ISSUE THREAD

**Issue by mbbroberg** [chaoss/wg-value#74]
[This metric](https://github.com/chaoss/wg-value/blob/master/metrics/archived/job-opportunities.md) is scoped as a view on whether a Developer should invest in certain skills based on the frequency of mention of that skill in job postings. This framing does not fit directly into our mission, so this issue is a place to continue the discussion on how it may fit in. 

One angle: A VC publicly mentioned tracking of job postings as a signal for investment in [this article on the BOSS index](https://www.battery.com/powered/boss-index-tracking-explosive-growth-open-source-software/). We could generalize this premise as a metric community leaders could track to show a growing adoption of the project/product. 

I believe this differs in scope from [popularity metrics](https://github.com/chaoss/wg-value/blob/master/metrics/project_popularity.md) since it's specifically about using this information to show value. I would also like to avoid popularity becoming a catch all for the month-over-month metrics used to justify investment... but that's just a hunch. Let's discuss further.

**Comment by mbbroberg** [comment]
@vinodkahuja / @klumb I would love your perspectives in particular based on today's call.

**Comment by klumb** [comment]
Just some general musings...

The job posting aspect is just one way to measure the importance of knowledge or a skillset (and not terribly interesting to me). 

The skill is a valuable resource so perhaps the skill is the metric. Organizations want it, contributors or employees want to provide it.

If we view the knowledge or skillset as a resource, I think we can picture it using a simple supply and demand model.  

Organizations or projects may place value on the resource. Scarcity of the resource will make it more valuable. Scarcity of the resource may mean more individuals seek to provide the resource. 

So the number of contributors in a project and their skillset may be a way of representing value for the organization or project and identifying opportunities for individuals. 

Maybe this metric becomes - 
Developer Skill or Knowledge (human resource focus area?)
From an organizational or project perspective, the individual is a resource or an asset. 
i.e. if my organization uses python, python developers are a resource. Depending on scarcity, we may want to find or train more. If the organization or project has many python developers that's probably a good thing.

At the project level, we might be able to measure this by the language or technology used in a project (or the project technology itself - Kubernetes) and the number of contributors. This metric could inform value decisions around human resources and organization/project interdependencies.

**Comment by klumb** [comment]
Regarding the VC angle, I believe that could be a metric but I think it would be limited to only a few large and incredibly successful projects - Kubernetes, Linux Kernal, Hyperledger, and etc...

**Comment by mbbroberg** [comment]
Interesting points - thanks for weighing in @klumb. Some thoughts: 

I appreciate the angle of supply and demand and the idea of putting a value (almost a multiplier) on a given skill set. For instance, if my organization values one metric developer as $100k a year, but we are in need of Python skills, I could consider any Python developer that meets that bar worth 40% over standard rate, or $140k a year. While HR practices are generally not public or explicit like this, it could resemble that process behind the scenes. 

The question that remains for me is in what scenario is this math going to impact the decision to fund community work? 

I'm not sure. 

And some specific points --- 

> This metric could inform value decisions around human resources and organization/project interdependencies.

I wouldn't consider HR a decision-maker when it comes to funding community work. In practice, their scope centers on risk avoidance rather than funding (the latter being an executive function). 

Said another way, if the metric is primarily a function of HR or the gaps between organizations like interdependence, I don't believe it can be considered one of value as we've scoped it. 

I do **love the idea of focus areas centering on value-oriented business units**. In practice, Community organizations tend to fall under either Product/Engineering or Marketing. They do have different formulations of value, and I can speak from experience in saying metrics fall on deaf ears if you use the wrong ones in each organization. 

> I think it would be limited to only a few large and incredibly successful projects

I can confirm the opposite -- it's used as an indicator of the opportunity to invest in undervalued and underinvested projects. It's been used to show adoption and brand affinity for smaller projects that ultimately turn into a SaaS or open core approach to business.

**Comment by klumb** [comment]
To be clear, I am not referring to Human Resources as a department in an organization. I am referring to developer skillset or knowledge as a resource. When organizations engage in open source most often it is by providing resources in the form of employees, or employee time.  To make decisions about this engagement, organizations need to understand the communities existing technology, knowledge, and where it would fit in the ecosystem/supply chain.

Perhaps this is a stretch from where the metric is currently. 

Regarding the VC angle, I defer to your knowledge of its limitations. 

_"The question that remains for me is in what scenario is this math going to impact the decision to fund community work?"_

If the VC angle provides information on "opportunity to invest", I suppose my musing is not necessarily about whether to invest but more about understanding what assets a community has and what they may need. However, I do believe these questions are generally important to investors.

**Comment by mbbroberg** [comment]
> To be clear, I am not referring to Human Resources as a department in an organization.

My mistake. Thanks for clarifying. 

I'm with you on the circling back to investment. Let's continue to collect feedback from others and see how this evolves.

**Comment by vinodkahuja** [comment]
The job opportunity metric was developed from the developer’s perspective. After the revival of the value group with a new mission, I don’t feel it fits with any of the focus areas. 
My suggestion would be first redefining our focus area in alignment with our new mission statement and then think whether the proposed metric fit in the focus area or not. If it does not fit then we can propose moving this metric to the common metric group.

Further, I like @klumb's idea of looking into high knowledge/skill demand as a value option. That can be further discussed once our focus areas are refined.

**Comment by GeorgLink** [comment]
Could Job Opportunity be used in combination with Share of Voice? 

Example Red Hat. Project Ansible. There are other projects that solve the same problem. Looking at Job Opportunities for Ansible skills compared to a baseline skillset (or specifically competing technologies) may inform Red Hat of the success or decline of the project, possibly driving budgeting decisions for their engineering and community efforts.

Side note: Someone I talked to this week used the "job opportunity" metric when we were talking about the sustainability of their project. I don't have my notes with me to remember the specifics.

**Comment by LawrenceHecht** [comment]
@GeorgLink don't use Job Opportunity in Share of Voice. SoV is already a very confusing metric.

@mbbroberg and everyone else. Job opportunity is not a value metric unto itself. Instead, it is an input into other metrics, such as sustainability.

**Comment by klumb** [comment]
Thanks, @LawrenceHecht 

That was part of my point - as written, job opportunity is a very specific way to measure the value of a skill or technology to a developer. Job opportunity itself isn't really a metric.

**Comment by mbbroberg** [comment]
Thanks all for the discussion. I'm in agreement that it isn't a metric as written. 

@klumb or @GeorgLink with the assumption it's important to keep this for future releases, do either of you have recommendations on reframing so that job opportunity is a value metric? 

Note for others: PRs encouraged. This change needs an owner.

**Comment by mbbroberg** [comment]
Fixed in 0f62007
