### ISSUE TITLE
Focus area proposal: Reputation

### ISSUE THREAD

**Issue by mbbroberg** [chaoss/wg-value#84]
The importance of focus areas came up in today's meeting, which centered on #76 & #77. We got close to defining Goal -> Metric -> Questions approach around understanding external voice. 

The term `Reputation` comes to mind as a commonly understood category that covers the goals of these metric. 

- The question for others here: does it make sense under our current charter? 
- If yes, what questions follow?

The desired outcome for this issue is to do the following: 

- [ ] Discuss whether Reputation is a worthwhile area of focus for Value 
- [ ] If yes, resolve this issue by opening a PR similar structure to D&I's with:
  - [ ] A table of focus areas
  - [ ] Goals for Reputation
  - [ ] Subdirectory with a table of questions to be answered by metrics

**Comment by germonprez** [comment]
Thanks for this @mbbroberg 

Yes, I believe Reputation is a great name for a focus area. Short and simple.

**Comment by samanthavenialogan** [comment]
Agreed.

Samantha Venia Logan
Co-Founder of SociallyConstructed.Online
307-274-5516  | samantha@SociallyConstructed.Online
6715 Autumn Ridge Dr. Unit 2, Fort Collins CO., 80525

Call me for a free marketing consultation! 307-274-5516

**Comment by mbbroberg** [comment]
Closing this in favor of #93
