### ISSUE TITLE
Complete 'Project Popularity' metric

### ISSUE THREAD

**Issue by mbbroberg** [chaoss/wg-value#85]
The [current version](https://github.com/chaoss/wg-value/blob/master/metrics/project_popularity.md) is missing most of its implementation details. Is there someone in this group who would like to take a swing at a PR to update it? 

See #84 for context.

**Comment by germonprez** [comment]
Thanks @mbbroberg 

I've placed the metric into a shared document. It's a bit easier to collectively edit and track comments. Once done, we can issue a PR with this as a new metric. 

https://docs.google.com/document/d/12zGoQHkyGQrjp_WuSA_fk_PvaJP7H0Zw_f3LtnrODZY/edit?usp=sharing

I've also started tracking work on metrics that are emerging from the discussions. This includes Share-of-Voice and Project Popularity

https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit#gid=700620500

**Comment by mbbroberg** [comment]
From original issue: 

- Number of source code download
- Number of subscriber
- Number of stars
- Number of watchers
- Number of followers
- User ratings
- Appearance on the top list of google search or other blogs

**Comment by GeorgLink** [comment]
We have watchers, stars, and forks for CHAOSS in the CHAOSS Community Dashboard: https://chaoss.biterg.io/app/kibana#/dashboard/8035e0c0-45e6-11e9-b68b-31a1aa44b23a

**Comment by mbbroberg** [comment]
I have a full draft of Popularity (Reputation) ready for review - https://docs.google.com/document/d/12zGoQHkyGQrjp_WuSA_fk_PvaJP7H0Zw_f3LtnrODZY/edit#

**Comment by mbbroberg** [comment]
We had a great conversation in today's meeting (next meeting is Oct 22). 

Some notes: 

- Reputation as a leading indicator (more about _who’s_ participating and _where_)
  - Stars and Forks on other repositories affiliated with an organization
  - Followers of developers/contributors (people follow the popular contributors, Blincoe, et. al, 2016) 
  - Social media reputation
    - Twitter Followers
    - Facebook Friends
    - Instagram Followers 
  - Public presence of developers/contributors (talks, blog posts, etc)
- Development & Usage as a lagging indicator (a market share perspective on popularity)
  - one doesn’t have market share until there’s a market
  - At this point, comparative metrics about the project itself matter
  - The social prowess of participants is still a factor

The question remains whether we're capturing a single metric or multiple.

**Comment by nicorikken** [comment]
Not sure if I should post it here first or just add it to the document. This seems most like a request, so I'll do it here for now.

I noticed GitHub has added some more metrics that might be worthwhile to consider.

* Aside of number of clones, one can also look at the number of unique clones, and view them both over time.
* Pageviews can be monitored. As a metric this can be very broad to include pageview on documentation and the main website, which could of course could be drilled down per destination. Pageviews are also available as generic metric and by unique visitor.
* Pageviews are available per page. Not sure if this is too specific for the current considerations of CHAOSS, as it is a level within the repo itself.
* 
![image](https://user-images.githubusercontent.com/7458098/126382061-1b17d946-4132-459b-82b6-34964d8a91fd.png)
