### ISSUE TITLE
Focus area proposal: Economic value

### ISSUE THREAD

**Issue by vinodkahuja** [chaoss/wg-value#87]
**Goal:** To identify metrics that help to measure how various stakeholders drive economic value from open source.

One already released metric is labor investment that we can move to this focus area. Similarly, we can brainstorm for other metrics like different revenue streams and opensourcing.

Any other ideas for metrics for the proposed focus group are most welcome.

Note: I got the concept of open sourcing from the following article.
Ågerfalk, P. and Fitzgerald, B. 2008. Outsourcing to an Unknown Workforce: Exploring Opensourcing as a Global Sourcing Strategy. MIS Quarterly. 32(2) 385-409.

**Comment by mbbroberg** [comment]
Closing this in favor of #93
