### ISSUE TITLE
For release review cycle: redesigned focus areas

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-value#95]
The Value Working Group redesigned the focus areas:
https://github.com/chaoss/wg-value/tree/master/focus-areas/

All released metrics are organized in this new structure. 
There is no new Value metric for this release.

This issue is for capturing feedback during the release review cycle.

**Comment by klumb** [comment]
This issue was created to capture the continuous release notes. Insight from comments will be used to create the regular release note.

Example comments could be:

    name of new metric and date of release
    descriptions of changes to existing metric
    Changes to focus areas or restructuring of WG

**Comment by GeorgLink** [comment]
Release notes for Value WG:
- Restructured the focus areas
- All previously released metrics are assigned one of the new focus areas
- Minor updates to Social Currency Metric System (SCMS)

NOTE: Do not release the empty Social Value focus area

**Comment by mbbroberg** [comment]
Totally biased but I love this change :shipit:

**Comment by klumb** [comment]
closing for release 2020-08
